### ISSUE TITLE
Syntax Highlighting for UnoCSS in VS Code?

### ISSUE THREAD

**Issue by niklasgrewe** [johannschopplich/kirby-vite-unocss-kit#3]
Hi,
thank you very much for this template. The only thing i missed, is the syntax highlighting for unocss inside my `.php` files. Do you find a way to get this working without breaking the php syntax?

**Comment by johannschopplich** [comment]
I haven't managed to make the UnoCSS VSCode extension work with PHP files, either. ~~Probably a config option. But didn't find it yet.~~ 

Although PHP files itself [are supported](https://github.com/unocss/unocss/blob/e0bfe142091e403c02ddb70b8ff7474887032fba/packages/vscode/src/autocomplete.ts#L21). 

I will have to look into it another day. If you find a solution, feel free to share!

**Comment by johannschopplich** [comment]
@niklasgrewe With the latest versions of the [UnoCSS VSCode extension](https://marketplace.visualstudio.com/items?itemName=antfu.unocss), it's finally working.

Reference:

<img width="909" alt="grafik" src="https://user-images.githubusercontent.com/27850750/210741121-dfe8b995-5767-4ebc-8d8d-fbbe74a9d9b1.png">
